// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Choosy",
  handlers: [
    {
      match: ({ opener }) => opener.bundleId === "com.tinyspeck.slackmacgap",
      browser: {
        name: "com.vivaldi.Vivaldi",
        profile: "Default",
      },
    },
    {
      match: /^https?:\/\/.*\.salesforce\.com$/,
      browser: {
        name: "com.vivaldi.Vivaldi",
        profile: "Default",
      },
    },
    {
      match: /^https?:\/\/.*\.internal\.salesforce\.com$/,
      browser: {
        name: "com.vivaldi.Vivaldi",
        profile: "Default",
      },
    },
    {
      match: "open.spotify.com/*",
      browser: "Spotify",
    },
  ],
};
